name: Bench
on:
  pull_request:
    branches:
    - '*'

permissions:
  contents: write
  deployments: write

jobs:
  benchmark:
    name: Run Go benchmarks
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4

    - name: Run benchmark
      run: go test -bench '.*' | tee bench.out

    - name: Store benchmark result
      uses: benchmark-action/github-action-benchmark@v1
      with:
        name: Go Benchmark
        tool: 'go'
        output-file-path: bench.out
        github-token: ${{ secrets.GITHUB_TOKEN }}
        auto-push: false
        # Show alert with commit comment on detecting possible performance regression
        alert-threshold: '110%'
        comment-on-alert: false
        # Enable Job Summary for PRs
        summary-always: true
        fail-on-alert: false
        alert-comment-cc-users: '@pmalek'
